export const DOMAIN_ERROR_CODES = [
  'FULLNAME.NOT_STRING',
  'FULLNAME.EMPTY',
  'FULLNAME.TOO_SHORT',
  'FULLNAME.TOO_LONG',
  'FULLNAME.INVALID_CHARACTER',

  'PASSWORD.NOT_STRING',
  'PASSWORD.EMPTY',
  'PASSWORD.TOO_SHORT',

  'TOKEN.NOT_STRING',
  'TOKEN.EMPTY',

  'USERNAME.NOT_STRING',
  'USERNAME.EMPTY',
  'USERNAME.TOO_SHORT',
  'USERNAME.TOO_LONG',
  'USERNAME.INVALID_CHARACTER',

  'USER_ID.EMPTY',
] as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[number];
