export const DOMAIN_ERROR_CODES = [
  'FULLNAME.NOT_STRING',
  'FULLNAME.EMPTY',
  'FULLNAME.TOO_SHORT',
  'FULLNAME.TOO_LONG',
  'FULLNAME.INVALID_CHARACTER',

  'PASSWORD.NOT_STRING',
  'PASSWORD.EMPTY',
  'PASSWORD.TOO_SHORT',

  'TOKEN.NOT_STRING',
  'TOKEN.EMPTY',

  'USERNAME.NOT_STRING',
  'USERNAME.EMPTY',
  'USERNAME.TOO_SHORT',
  'USERNAME.TOO_LONG',
  'USERNAME.INVALID_CHARACTER',
  'USERNAME.NOT_AVAILABLE',
  'USERNAME_AND_PASSWORD.EMPTY',

  'USER_ID.EMPTY',
  'AUTH_USER.NOT_FOUND',

  'REFRESH_TOKEN.NOT_REGISTERED',
  'REFRESH_TOKEN.EMPTY',
  'REFRESH_TOKEN.NOT_STRING',

  'THREAD_ID.EMPTY',
  'THREAD_BODY.NOT_STRING',
  'THREAD_BODY.EMPTY',
  'THREAD_TITLE.NOT_STRING',
  'THREAD_TITLE.EMPTY',

  'COMMENT_ID.EMPTY',
  'COMMENT_CONTENT.NOT_STRING',
  'COMMENT_CONTENT.EMPTY',
] as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[number];
